spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: anis
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: admin
      password: admin

server:
  port:8080